[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pandas",
    "numpy",
    "scikit-learn",
    "seaborn",
    "matplotlib",
    "wordcloud",
    "plotly",
    "xgboost",
    "opencv-python",
    "unidecode",
    "emoji",
    "textblob",
    "contextily",
]
build-backend = "setuptools.build_meta"